#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

# Use matplotlib to generate the graphic for the 
# http://www.physics-geek.us discussion on transverse waves

x = np.linspace(-1, 15, 512)
#f = np.piecewise(x,
#[x < 8, x >= 8], 
#[lambda x : 10*np.exp((x-8)**2)/(2)-2, lambda x : 5*np.exp((x-8)**2)/(2)+3]
#)
f = np.piecewise(x, 
[x < 8, x >=8],
[lambda x: (5/(np.sqrt(2*np.pi)))*(np.exp(-((x-8)**2/20)))-0.05,
lambda x: (4/(np.sqrt(2*np.pi)))*(np.exp(-((x-8)**2/15)))+0.35])
plt.plot(x, f)
plt.quiver(0, 0, 0, 10, angles='uv', scale=15)
plt.quiver(0, 0, 15, 0, angles='uv', scale=18)
plt.axis('off')
plt.show()